#spring: 
#  datasource: 
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#  mvc: 
#    view: 
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp